import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  dsaSidebar: [{type: 'autogenerated', dirName: 'dsa'}],
  webDevelopmentSidebar: [{type: 'autogenerated', dirName: 'web-development'}],
  systemDesignSidebar: [{type: 'autogenerated', dirName: 'system-design'}],
};

export default sidebars;
