import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const dsaSidebar = [
  {
    type: 'category',
    label: 'DSA',
    link: {
      type: 'generated-index',
      title: 'DSA',
      slug: '/dsa',
      description: 'Data Structures and Algorithms study notes.',
    },
    collapsed: false,
    items: [
      'dsa/resources',
      'dsa/coding-round',
      'dsa/concepts',
      'dsa/js-vs-java',
      'dsa/toll-increase',
      'dsa/problems-solved',
    ],
  },
] satisfies SidebarsConfig[string];

const systemDesignSidebar = [
  {
    type: 'category',
    label: 'System Design',
    link: {
      type: 'generated-index',
      title: 'System Design',
      slug: '/system-design',
      description: 'System Design study notes.',
    },
    collapsed: false,
    items: [
      {
        type: 'category',
        label: 'System Design Basics',
        link: {
          type: 'doc',
          id: 'system-design/system-design-basics/index',
        },
        items: [
          'system-design/system-design-basics/interview-framework',
          'system-design/system-design-basics/google-session-chat-service',
        ],
      },
      {
        type: 'category',
        label: 'Core Concepts',
        link: {
          type: 'doc',
          id: 'system-design/core-concepts/index',
        },
        items: [
          'system-design/core-concepts/scalability-reliability',
          'system-design/core-concepts/caching-cdn',
          'system-design/core-concepts/databases-partitioning',
          'system-design/core-concepts/queues-event-driven-systems',
          'system-design/core-concepts/rate-limiting-resilience',
          'system-design/core-concepts/observability',
        ],
      },
      {
        type: 'category',
        label: 'Frontend System Design',
        link: {type: 'doc', id: 'system-design/frontend-system-design/index'},
        items: [
          'system-design/frontend-system-design/design-large-dashboard',
          'system-design/frontend-system-design/design-google-docs',
          'system-design/frontend-system-design/design-netflix-ui',
          'system-design/frontend-system-design/design-linkedin-feed',
          'system-design/frontend-system-design/design-admin-portal',
          'system-design/frontend-system-design/design-component-library',
          'system-design/frontend-system-design/design-microfrontend-platform',
          'system-design/frontend-system-design/design-real-time-notification-ui',
          'system-design/frontend-system-design/design-large-tree-view',
          'system-design/frontend-system-design/design-search-autocomplete-ui',
          'system-design/frontend-system-design/design-analytics-reporting-ui',
          'system-design/frontend-system-design/design-multi-tenant-saas-frontend',
        ],
      },
      {
        type: 'category',
        label: 'Backend / Distributed Systems',
        link: {type: 'doc', id: 'system-design/backend-distributed-system-design/index'},
        items: [
          'system-design/backend-distributed-system-design/url-shortener',
          'system-design/backend-distributed-system-design/autocomplete',
          'system-design/backend-distributed-system-design/google-search',
          'system-design/backend-distributed-system-design/notification-system',
          'system-design/backend-distributed-system-design/chat-system',
          'system-design/backend-distributed-system-design/news-feed',
          'system-design/backend-distributed-system-design/file-upload-system',
          'system-design/backend-distributed-system-design/video-streaming',
          'system-design/backend-distributed-system-design/payment-system',
          'system-design/backend-distributed-system-design/rate-limiter',
          'system-design/backend-distributed-system-design/logging-platform',
          'system-design/backend-distributed-system-design/metrics-platform',
          'system-design/backend-distributed-system-design/real-time-analytics',
          'system-design/backend-distributed-system-design/ad-tech-platform',
          'system-design/backend-distributed-system-design/campaign-management-system',
          'system-design/backend-distributed-system-design/siem-security-event-platform',
          'system-design/backend-distributed-system-design/feature-flag-system',
          'system-design/backend-distributed-system-design/multi-tenant-saas-platform',
          'system-design/backend-distributed-system-design/access-control-system',
        ],
      },
      {
        type: 'category',
        label: 'Data & Storage',
        link: {type: 'doc', id: 'system-design/data-storage-design/index'},
        items: [
          'system-design/data-storage-design/database-selection',
          'system-design/data-storage-design/data-modeling',
          'system-design/data-storage-design/indexing-and-querying',
          'system-design/data-storage-design/partitioning-and-sharding',
          'system-design/data-storage-design/consistency-and-sync',
          'system-design/data-storage-design/read-write-patterns',
        ],
      },
      {
        type: 'category',
        label: 'API & Communication',
        link: {type: 'doc', id: 'system-design/api-communication-design/index'},
        items: [
          'system-design/api-communication-design/api-styles',
          'system-design/api-communication-design/realtime-communication',
          'system-design/api-communication-design/api-gateway-and-bff',
          'system-design/api-communication-design/reliability-patterns',
          'system-design/api-communication-design/payload-optimization',
        ],
      },
      {
        type: 'category',
        label: 'Cloud / Infra',
        link: {type: 'doc', id: 'system-design/cloud-devops-infra/index'},
        items: [
          'system-design/cloud-devops-infra/containers-and-orchestration',
          'system-design/cloud-devops-infra/scaling-and-service-discovery',
          'system-design/cloud-devops-infra/deployment-strategies',
          'system-design/cloud-devops-infra/ci-cd-and-environments',
          'system-design/cloud-devops-infra/logging-metrics-alerts',
        ],
      },
      {
        type: 'category',
        label: 'Security',
        link: {type: 'doc', id: 'system-design/security-system-design/index'},
        items: [
          'system-design/security-system-design/authentication-and-authorization',
          'system-design/security-system-design/access-control',
          'system-design/security-system-design/token-and-session-security',
          'system-design/security-system-design/encryption-and-secrets',
          'system-design/security-system-design/audit-compliance-pii',
          'system-design/security-system-design/secure-api-design',
        ],
      },
      {
        type: 'category',
        label: 'Question Bank',
        link: {type: 'doc', id: 'system-design/system-design-question-bank/index'},
        items: [
          'system-design/system-design-question-bank/easy',
          'system-design/system-design-question-bank/medium',
          'system-design/system-design-question-bank/hard',
          'system-design/system-design-question-bank/staff-level',
          'system-design/system-design-question-bank/recently-asked',
          'system-design/system-design-question-bank/company-asked',
          'system-design/system-design-question-bank/solved',
          'system-design/system-design-question-bank/need-revision',
        ],
      },
      {
        type: 'category',
        label: 'Templates',
        link: {type: 'doc', id: 'system-design/system-design-templates/index'},
        items: [
          'system-design/system-design-templates/five-minute-answer-template',
          'system-design/system-design-templates/thirty-minute-interview-template',
          'system-design/system-design-templates/frontend-system-design-template',
          'system-design/system-design-templates/backend-system-design-template',
          'system-design/system-design-templates/trade-off-checklist',
          'system-design/system-design-templates/deep-dive-checklist',
        ],
      },
      'system-design/resources',
    ],
  },
] satisfies SidebarsConfig[string];

const webDevelopmentSidebar = [
  {
    type: 'category',
    label: 'Web Development',
    link: {
      type: 'generated-index',
      title: 'Web Development',
      slug: '/web-development',
      description: 'Web Development study notes.',
    },
    collapsed: false,
    items: [
      {
        type: 'category',
        label: 'Interview Prep Order',
        link: {type: 'doc', id: 'web-development/interview-prep-order/index'},
        items: [
          'web-development/interview-prep-order/phase-wise',
          'web-development/interview-prep-order/chatgpt-checklist',
        ],
      },
      {
        type: 'category',
        label: 'Companies',
        items: [
          'web-development/companies/adobe',
          {
            type: 'category',
            label: 'Agoda',
            link: {type: 'doc', id: 'web-development/companies/agoda/index'},
            items: [
              'web-development/companies/agoda/coding-round-1',
              'web-development/companies/agoda/platform-round-2',
              'web-development/companies/agoda/screening-round',
            ],
          },
          {
            type: 'category',
            label: 'OneTrust',
            items: ['web-development/companies/onetrust/jd'],
          },
          'web-development/companies/arcticwolf',
          'web-development/companies/walmart',
          'web-development/companies/samsung-dsp',
          'web-development/companies/forbes-advisor',
        ],
      },
      {
        type: 'category',
        label: 'Web Fundamentals',
        link: {type: 'doc', id: 'web-development/web-fundamentals/index'},
        items: [
          'web-development/web-fundamentals/url-in-browser',
          'web-development/web-fundamentals/browser-rendering-pipeline',
        ],
      },
      {
        type: 'category',
        label: 'Core Engineering',
        link: {type: 'doc', id: 'web-development/important/index'},
        items: [
          {
            type: 'category',
            label: 'Performance',
            link: {type: 'doc', id: 'web-development/important/performance/index'},
            items: [
              'web-development/important/performance/generic-web-performance',
              'web-development/important/performance/core-web-vitals',
              'web-development/important/performance/lighthouse-and-tools',
              'web-development/important/performance/rendering',
              'web-development/important/performance/react-performance',
              'web-development/important/performance/nextjs-performance',
              'web-development/important/performance/monitoring-observability',
            ],
          },
          'web-development/important/error-handling',
          {
            type: 'category',
            label: 'Testing & Quality',
            link: {type: 'doc', id: 'web-development/important/testing/index'},
            items: ['web-development/important/testing/react-testing'],
          },
          {
            type: 'category',
            label: 'Security & Auth',
            link: {type: 'doc', id: 'web-development/important/security/index'},
            items: [
              'web-development/important/security/jwt-csrf',
              'web-development/important/security/owasp',
              'web-development/important/security/iframe-protection',
              'web-development/important/security/xss-cross-site-scripting',
              'web-development/important/security/security-headers',
              'web-development/important/security/react-security',
              'web-development/important/security/frontend-security-checklist',
            ],
          },
          'web-development/important/caching',
          'web-development/important/observability',
          'web-development/important/frontend-architecture',
          'web-development/important/memory-management',
          'web-development/important/quick-questions',
          'web-development/important/accessibility',
          'web-development/important/backend-for-fe-bff',
          'web-development/important/solid',
          'web-development/important/code-review-checklist',
          {
            type: 'category',
            label: 'UX | Design System',
            link: {type: 'doc', id: 'web-development/important/ux-design-system/index'},
            items: ['web-development/important/ux-design-system/storybook'],
          },
          'web-development/important/micro-frontends',
        ],
      },
      {
        type: 'category',
        label: 'JavaScript',
        link: {type: 'doc', id: 'web-development/javascript/index'},
        items: [
          {
            type: 'category',
            label: 'JavaScript Under The Hood',
            link: {type: 'doc', id: 'web-development/javascript/javascript-under-the-hood/index'},
            items: [
              'web-development/javascript/javascript-under-the-hood/js-engine',
              'web-development/javascript/javascript-under-the-hood/garbage-collector-internals',
            ],
          },
          {
            type: 'category',
            label: 'Interview Q&A',
            link: {type: 'doc', id: 'web-development/javascript/interview-q-a/index'},
            items: ['web-development/javascript/interview-q-a/quick-q-a-js'],
          },
          'web-development/javascript/js-evaluation',
          'web-development/javascript/execution-context',
          'web-development/javascript/js-fundamentals',
          'web-development/javascript/scope',
          'web-development/javascript/hoisting',
          'web-development/javascript/strict-mode',
          'web-development/javascript/event-loop',
          'web-development/javascript/objects-prototypes',
          'web-development/javascript/functions',
          'web-development/javascript/this-keyword',
          'web-development/javascript/call-bind-apply',
          'web-development/javascript/closures',
          'web-development/javascript/classes-oop',
          'web-development/javascript/arrays-collections',
          'web-development/javascript/strings',
          'web-development/javascript/temporal-new',
          'web-development/javascript/asynchronous-javascript',
          'web-development/javascript/es6-features',
          'web-development/javascript/memory-management',
          'web-development/javascript/modules',
          'web-development/javascript/advanced-js',
          'web-development/javascript/browser-apis-dom',
          'web-development/javascript/error-handling',
          'web-development/javascript/design-patterns',
          'web-development/javascript/javascript-coding-questions',
        ],
      },
      {
        type: 'category',
        label: 'TypeScript',
        link: {type: 'doc', id: 'web-development/typescript/index'},
        items: [
          'web-development/typescript/chatgpt-notes',
          'web-development/typescript/ts-concepts',
          'web-development/typescript/code',
        ],
      },
      {
        type: 'category',
        label: 'React.js',
        link: {type: 'doc', id: 'web-development/react-js/index'},
        items: [
          {
            type: 'category',
            label: 'Fundamentals',
            link: {type: 'doc', id: 'web-development/react-js/fundamentals/index'},
            items: [
              'web-development/react-js/fundamentals/functional-components-vs-class-components',
            ],
          },
          {
            type: 'category',
            label: 'Rendering & Internals',
            link: {type: 'doc', id: 'web-development/react-js/react-under-the-hood'},
            items: [
              'web-development/react-js/rendering-components',
              'web-development/react-js/fundamentals/react-pipeline',
              'web-development/react-js/fundamentals/reconciliation-1',
              'web-development/react-js/fundamentals/react-fiber',
            ],
          },
          'web-development/react-js/react-hooks',
          'web-development/react-js/state-management',
          'web-development/react-js/forms',
          'web-development/react-js/component-communication-patterns',
          'web-development/react-js/folder-structure',
          'web-development/react-js/core-concept-internals',
          'web-development/react-js/advanced-react-patterns',
          'web-development/react-js/error-handling-in-react',
          'web-development/react-js/react-router',
          'web-development/react-js/react-architecture',
          'web-development/react-js/react-under-the-hood',
          'web-development/react-js/coding',
        ],
      },
      {
        type: 'category',
        label: 'Next.js',
        link: {type: 'doc', id: 'web-development/next-js/index'},
        items: [
          'web-development/next-js/next-js-fundamentals',
          'web-development/next-js/routing',
          'web-development/next-js/rendering-strategies',
          'web-development/next-js/server-components-client-components',
          'web-development/next-js/data-fetching',
          'web-development/next-js/caching',
          'web-development/next-js/performance-optimization',
          'web-development/next-js/middleware',
          'web-development/next-js/authentication-authorization',
          'web-development/next-js/api-routes',
          'web-development/next-js/error-handling',
          'web-development/next-js/deployment-production',
          'web-development/next-js/next-js-architecture',
          'web-development/next-js/senior-staff-next-js-topics',
          'web-development/next-js/chatgpt-next',
        ],
      },
      {
        type: 'category',
        label: 'Node.js',
        link: {type: 'doc', id: 'web-development/node-js/index'},
        items: ['web-development/node-js/chatgpt-node'],
      },
      'web-development/html-css',
      'web-development/angular',
      'web-development/resources',
    ],
  },
] satisfies SidebarsConfig[string];

const resetSidebar = [
  'intro',
  {
    type: 'link',
    label: 'DSA',
    href: '/docs/dsa',
  },
  'web-development',
  {
    type: 'link',
    label: 'System Design',
    href: '/docs/system-design',
  },
  {
    type: 'link',
    label: 'Engineering Handbook',
    href: '/docs/intro',
  },
] satisfies SidebarsConfig[string];

const sidebars: SidebarsConfig = {
  dsaSidebar,
  webDevelopmentSidebar,
  systemDesignSidebar,
};

export default sidebars;
